### ISSUE TITLE
no such package available : @pact-foundation/pact-node

### ISSUE THREAD

**Issue by mikefarah** [pact-foundation/pact-js-mocha#1]
I added the dependency into the package.json as described, ran npm install and got this warning:

```
> npm WARN optional Skipping failed optional dependency /pact-mocha-interface/@pact-foundation/pact-node:
> npm WARN 404 no such package available : @pact-foundation/pact-node
```

**Comment by tarciosaraiva** [comment]
hey @mikefarah looking into it. Pact JS Mocha uses pact-node under the hood which, in turn, installs binaries for a mock server using Traveling Ruby for now. Sometimes we see this message as well but it doesn't cause troubles.

Have you managed to actually write any tests?

**Comment by tarciosaraiva** [comment]
Hey @mikefarah so the messages we usually get while installing it are below. They have to do with skipped dependencies not matching your architecture.

The one you're getting seems different. Which node and npm version you're running? We are not support `v0.12`, only `v4` upwards.

```
npm WARN optional Skipping failed optional dependency /@pact-foundation/pact-node/@pact-foundation/pact-provider-verifier-linux-x64:
npm WARN notsup Not compatible with your operating system or architecture: @pact-foundation/pact-provider-verifier-linux-x64@0.0.12
npm WARN optional Skipping failed optional dependency /@pact-foundation/pact-node/@pact-foundation/pact-provider-verifier-linux-ia32:
npm WARN notsup Not compatible with your operating system or architecture: @pact-foundation/pact-provider-verifier-linux-ia32@0.0.12
npm WARN optional Skipping failed optional dependency /@pact-foundation/pact-node/@pact-foundation/pact-provider-verifier-win32:
npm WARN notsup Not compatible with your operating system or architecture: @pact-foundation/pact-provider-verifier-win32@0.0.12
npm WARN optional Skipping failed optional dependency /@pact-foundation/pact-mock-service/@pact-foundation/pact-mock-service-linux-ia32:
npm WARN notsup Not compatible with your operating system or architecture: @pact-foundation/pact-mock-service-linux-ia32@0.9.0
npm WARN optional Skipping failed optional dependency /@pact-foundation/pact-mock-service/@pact-foundation/pact-mock-service-win32:
npm WARN notsup Not compatible with your operating system or architecture: @pact-foundation/pact-mock-service-win32@0.9.0
npm WARN optional Skipping failed optional dependency /@pact-foundation/pact-mock-service/@pact-foundation/pact-mock-service-linux-x64:
npm WARN notsup Not compatible with your operating system or architecture: @pact-foundation/pact-mock-service-linux-x64@0.9.0
npm WARN optional Skipping failed optional dependency /@pact-foundation/pact-node/@pact-foundation/pact-provider-verifier/@pact-foundation/pact-provider-verifier-linux-ia32:
npm WARN notsup Not compatible with your operating system or architecture: @pact-foundation/pact-provider-verifier-linux-ia32@0.0.12
npm WARN optional Skipping failed optional dependency /@pact-foundation/pact-node/@pact-foundation/pact-provider-verifier/@pact-foundation/pact-provider-verifier-linux-x64:
npm WARN notsup Not compatible with your operating system or architecture: @pact-foundation/pact-provider-verifier-linux-x64@0.0.12
npm WARN optional Skipping failed optional dependency /@pact-foundation/pact-node/@pact-foundation/pact-provider-verifier/@pact-foundation/pact-provider-verifier-win32:
npm WARN notsup Not compatible with your operating system or architecture: @pact-foundation/pact-provider-verifier-win32@0.0.12
```

**Comment by mikefarah** [comment]
I'm running node 6

**Comment by tarciosaraiva** [comment]
Cool, thanks @mikefarah. Here's what a sample `package.json` should look like - pay attention to line 7, where you tell `mocha` to use the interface.

https://gist.github.com/tarciosaraiva/bb9fffa4e5bf3bf45d87e1efe700fb08

Let me know how you go.

**Comment by mikefarah** [comment]
Ok found the culprit, we're using a private hosted npm registery, Sinopia. For some reason this does not know how to fetch '@pact-foundation/pact-node', must be some sort of scoping issue?

I'll have to hunt around for a fix, because we depend on some private libraries...

**Comment by tarciosaraiva** [comment]
This is an interesting issue, thanks for letting me know.

We're actually going to deprecate pact-node in the near future as we are
developing a native library to "replace" pact mock server (essentially
pact-node is an abstraction layer on top of Ruby that's transparent to you).

Not sure what to do about the scoping issue with organisations + Sinopia
though. In the meantime, you could try and request the package by hand by
pointing to the Github repository just like the way you're doing with
pact-js-mocha

Since you're using Node 6 it should flatten the dependency tree and require
the right thing.

Good luck!

**Comment by mikefarah** [comment]
Cool I'll give that a go. It would be good to get rid of the ruby dependency, we're running this in docker so it's not so transparent ;)

I just writing the provider side of the pact, I'm curious as to why it would need a pact server, doesn't it just send the requests directly to the running provider instance?

**Comment by mboudreau** [comment]
@mikefarah We have a private registry at work, but I really don't recommend you use your private registry as a 'mirror' of the real one on npmjs.org.  Mostly because it can be behind in terms of functionality.  I'm guessing that your issue that you're having is that your private registry might not work with scoped packages since this is a fairly new feature.

That being said, you should be able to make it work by adding this to your .npmrc within your project:

```
@pact-foundation:registry=https://registry.npmjs.org/
```

Essentially, this is telling your npm that for all `@pact-foundation` scoped packages, look at the npm registry instead of your private one.  

I hope that helps.  Cheers.

**Comment by tarciosaraiva** [comment]
@mikefarah it needs a Pact server because it is the Pact server who orchestrates the requests from the Pact file to the provider. Remember that `pact-node` runs `pact-mock-service-npm` which is just a wrapper around the [Ruby library](https://github.com/bethesque/pact-mock_service).

**Comment by mikefarah** [comment]
Cool thanks guys 👍
