### ISSUE TITLE
API changes commited to master branch broke our build

### ISSUE THREAD

**Issue by mikefarah** [pact-foundation/pact-js-mocha#4]
As this library is not yet published to NPM repo, any changes to master will be immediately pulled in as part of our build process. 

Yesterday there was an API change made to this repo, and therefore it broke our build. As a hack, we attempted to have a dependency on a specific git sha, but the dependencies of this repo still pick up from latest master from those dependencies. 

This causes much angst and sadness.

Either publish to npm, or have git tags that we can depend on.

**Comment by tarciosaraiva** [comment]
Hi @mikefarah I was hoping this wouldn't happen, for that, my apologies. I will push for the library to be published asap.

**Comment by mikefarah** [comment]
Awesome thanks :D

**Comment by uglyog** [comment]
Hi Mike, as this is still WIP we don't want to publish to NPM until @tarciosaraiva is happy with it. We could add a tag for your build until then.

**Comment by mikefarah** [comment]
Meh everything is WIP. 

Just publish with 'beta' or 'alpha' in the version. Better than getting everyone to point to master. Git tag would work, but then you'd need to manage git tags for all its dependencies, not to mention it's more annoying for people who want to use the library (e.g. our builds run in docker, and currently we have to install git inside the docker container to be able install the dep :( )

**Comment by tarciosaraiva** [comment]
errr @mikefarah it is actually 1.0.0-alpha

**Comment by mikefarah** [comment]
oh in the NPM repo?

**Comment by tarciosaraiva** [comment]
Nope in here: if you look at the `package.json` the "version" key reads "1.0.0-alpha"

**Comment by mikefarah** [comment]
Oh right, cool hehe

My point is you may as well publish to the NPM repo and have alpha in the version field, which you do :)

The project is public GIT anyway, with instructions on how to install it so that it points to git master. Publishing to NPM will just mean you won't break other peoples build when you update master ;)

**Comment by tarciosaraiva** [comment]
@mikefarah Just an update on this: I'm pushing both Pact JS and Pact JS Mocha to NPM today. Pact JS is going as RC but Mocha is going as Alpha as I'm still not 100% comfortable with the way it behaves. ~~and I'm going to change it again (specifically by removing the wrapping on `finalizePact` and `addInteraction` blocks).~~

I actually made the `addInteraction` block take an Array of interactions and the name is also pluralized: `addInteractions([...])`

Feel free to drop in any suggestions.

Cheers

**Comment by mikefarah** [comment]
Awesome, though pact-js-mocha still depends on the github version of pact-js (in the package.json it has a dep "pact": "github:pact-foundation/pact-js")

**Comment by tarciosaraiva** [comment]
Ya, I'm on the process of fixing that up. Will let you know.

**Comment by tarciosaraiva** [comment]
Here you go @mikefarah **https://github.com/pact-foundation/pact-js-mocha/releases/tag/1.0.1-alpha**
v1.0.1-alpha

**Comment by mikefarah** [comment]
Yay cheers :D
