### ISSUE TITLE
Verify error code interactions throws the error you're hoping to verify

### ISSUE THREAD

**Issue by sbagnallsta** [pact-foundation/pact-js-mocha#9]
the following interaction

```
addInteractions([{
    state: 'i have a list of projects',
    uponReceiving: 'a bad request for projects',
    withRequest: {
      method: 'get',
      path: '/projects'
    },
    willRespondWith: {
      status: 400,
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
      body: { reply: 'this is a 400' }
    }
  }])
```

cannot be verified as the mock server will throw the 400 error.

See http://stackoverflow.com/questions/42916617/writing-interactions-for-pact-js-mocha-that-respond-with-an-error for background.

**Comment by mefellows** [comment]
Thanks for this, as briefly mentioned on SO, the issue will be related to the fact it's using an [RC](https://github.com/pact-foundation/pact-js-mocha/blob/master/package.json#L70) of Pact JS, we are currently in the 2.x.x branch. This project is still currently in 'alpha'.

The interface is largely the same, but there are a few differences in how the Pact service is started.

I won't be able to look at this for some time, but I would welcome a PR that updates to the latest pact and gets this up to speed.

If this doesn't seem palatable to you, take a look at the [mocha](https://github.com/pact-foundation/pact-js/tree/master/examples/mocha) example - using Pact JS with mocha is a little bit of extra boilerplate, but quite straightforward.
